# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/grpc/booleforce/booleforce.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ml2.grpc.prop import prop_pb2 as ml2_dot_grpc_dot_prop_dot_prop__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ml2/grpc/booleforce/booleforce.proto\x1a\x18ml2/grpc/prop/prop.proto2\xa6\x01\n\nBooleForce\x12-\n\x08\x43heckSat\x12\x0e.CNFSatProblem\x1a\x0f.CNFSatSolution\"\x00\x12=\n\nTraceCheck\x12\x15.ResProofCheckProblem\x1a\x16.ResProofCheckSolution\"\x00\x12*\n\x10\x42inarizeResProof\x12\t.ResProof\x1a\t.ResProof\"\x00\x62\x06proto3')



_BOOLEFORCE = DESCRIPTOR.services_by_name['BooleForce']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOLEFORCE._serialized_start=67
  _BOOLEFORCE._serialized_end=233
# @@protoc_insertion_point(module_scope)
