# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/grpc/mealy/mealy.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aml2/grpc/mealy/mealy.proto\"\x1f\n\x0cMealyMachine\x12\x0f\n\x07machine\x18\x01 \x01(\t\"\'\n\x10MealyTransitions\x12\x13\n\x0btransitions\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml2.grpc.mealy.mealy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MEALYMACHINE']._serialized_start=30
  _globals['_MEALYMACHINE']._serialized_end=61
  _globals['_MEALYTRANSITIONS']._serialized_start=63
  _globals['_MEALYTRANSITIONS']._serialized_end=102
# @@protoc_insertion_point(module_scope)
