"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MealyMachine(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MACHINE_FIELD_NUMBER: builtins.int
    machine: builtins.str
    def __init__(
        self,
        *,
        machine: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["machine", b"machine"]) -> None: ...

global___MealyMachine = MealyMachine

@typing_extensions.final
class MealyTransitions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSITIONS_FIELD_NUMBER: builtins.int
    transitions: builtins.str
    def __init__(
        self,
        *,
        transitions: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["transitions", b"transitions"]) -> None: ...

global___MealyTransitions = MealyTransitions
