# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ml2.grpc.aalta import aalta_pb2 as ml2_dot_grpc_dot_aalta_dot_aalta__pb2


class AaltaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckSat = channel.unary_unary(
                '/Aalta/CheckSat',
                request_serializer=ml2_dot_grpc_dot_aalta_dot_aalta__pb2.LTLSatProblemAalta.SerializeToString,
                response_deserializer=ml2_dot_grpc_dot_aalta_dot_aalta__pb2.LTLSatSolutionAalta.FromString,
                )


class AaltaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckSat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AaltaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckSat': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSat,
                    request_deserializer=ml2_dot_grpc_dot_aalta_dot_aalta__pb2.LTLSatProblemAalta.FromString,
                    response_serializer=ml2_dot_grpc_dot_aalta_dot_aalta__pb2.LTLSatSolutionAalta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Aalta', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Aalta(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckSat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Aalta/CheckSat',
            ml2_dot_grpc_dot_aalta_dot_aalta__pb2.LTLSatProblemAalta.SerializeToString,
            ml2_dot_grpc_dot_aalta_dot_aalta__pb2.LTLSatSolutionAalta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
