# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/tools/strix/strix.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from ml2.tools.protos import ltl_pb2 as ml2_dot_tools_dot_protos_dot_ltl__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="ml2/tools/strix/strix.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1bml2/tools/strix/strix.proto\x1a\x1aml2/tools/protos/ltl.proto"\x8a\x01\n\x0cStrixProblem\x12(\n\rspecification\x18\x01 \x01(\x0b\x32\x11.LTLSpecification\x12\x16\n\x0eminimize_aiger\x18\x02 \x01(\x08\x12\x16\n\x0eminimize_mealy\x18\x03 \x01(\x08\x12\x0f\n\x07threads\x18\x04 \x01(\x05\x12\x0f\n\x07timeout\x18\x05 \x01(\x02"/\n\rStrixSolution\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06system\x18\x02 \x01(\t2o\n\x05Strix\x12-\n\nSynthesize\x12\r.StrixProblem\x1a\x0e.StrixSolution"\x00\x12\x37\n\x10SynthesizeStream\x12\r.StrixProblem\x1a\x0e.StrixSolution"\x00(\x01\x30\x01\x62\x06proto3',
    dependencies=[
        ml2_dot_tools_dot_protos_dot_ltl__pb2.DESCRIPTOR,
    ],
)

_STRIXPROBLEM = _descriptor.Descriptor(
    name="StrixProblem",
    full_name="StrixProblem",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="specification",
            full_name="StrixProblem.specification",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="minimize_aiger",
            full_name="StrixProblem.minimize_aiger",
            index=1,
            number=2,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="minimize_mealy",
            full_name="StrixProblem.minimize_mealy",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="threads",
            full_name="StrixProblem.threads",
            index=3,
            number=4,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="timeout",
            full_name="StrixProblem.timeout",
            index=4,
            number=5,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=60,
    serialized_end=198,
)

_STRIXSOLUTION = _descriptor.Descriptor(
    name="StrixSolution",
    full_name="StrixSolution",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="status",
            full_name="StrixSolution.status",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="system",
            full_name="StrixSolution.system",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=200,
    serialized_end=247,
)

_STRIXPROBLEM.fields_by_name[
    "specification"
].message_type = ml2_dot_tools_dot_protos_dot_ltl__pb2._LTLSPECIFICATION
DESCRIPTOR.message_types_by_name["StrixProblem"] = _STRIXPROBLEM
DESCRIPTOR.message_types_by_name["StrixSolution"] = _STRIXSOLUTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StrixProblem = _reflection.GeneratedProtocolMessageType(
    "StrixProblem",
    (_message.Message,),
    {
        "DESCRIPTOR": _STRIXPROBLEM,
        "__module__": "ml2.tools.strix.strix_pb2"
        # @@protoc_insertion_point(class_scope:StrixProblem)
    },
)
_sym_db.RegisterMessage(StrixProblem)

StrixSolution = _reflection.GeneratedProtocolMessageType(
    "StrixSolution",
    (_message.Message,),
    {
        "DESCRIPTOR": _STRIXSOLUTION,
        "__module__": "ml2.tools.strix.strix_pb2"
        # @@protoc_insertion_point(class_scope:StrixSolution)
    },
)
_sym_db.RegisterMessage(StrixSolution)

_STRIX = _descriptor.ServiceDescriptor(
    name="Strix",
    full_name="Strix",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=249,
    serialized_end=360,
    methods=[
        _descriptor.MethodDescriptor(
            name="Synthesize",
            full_name="Strix.Synthesize",
            index=0,
            containing_service=None,
            input_type=_STRIXPROBLEM,
            output_type=_STRIXSOLUTION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="SynthesizeStream",
            full_name="Strix.SynthesizeStream",
            index=1,
            containing_service=None,
            input_type=_STRIXPROBLEM,
            output_type=_STRIXSOLUTION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_STRIX)

DESCRIPTOR.services_by_name["Strix"] = _STRIX

# @@protoc_insertion_point(module_scope)
