# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/tools/bosy/bosy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from ml2.tools.protos import ltl_pb2 as ml2_dot_tools_dot_protos_dot_ltl__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="ml2/tools/bosy/bosy.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x19ml2/tools/bosy/bosy.proto\x1a\x1aml2/tools/protos/ltl.proto"Z\n\x0b\x42oSyProblem\x12(\n\rspecification\x18\x01 \x01(\x0b\x32\x11.LTLSpecification\x12\x10\n\x08optimize\x18\x02 \x01(\x08\x12\x0f\n\x07timeout\x18\x03 \x01(\x02".\n\x0c\x42oSySolution\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06system\x18\x02 \x01(\t2j\n\x04\x42oSy\x12+\n\nSynthesize\x12\x0c.BoSyProblem\x1a\r.BoSySolution"\x00\x12\x35\n\x10SynthesizeStream\x12\x0c.BoSyProblem\x1a\r.BoSySolution"\x00(\x01\x30\x01\x62\x06proto3',
    dependencies=[
        ml2_dot_tools_dot_protos_dot_ltl__pb2.DESCRIPTOR,
    ],
)

_BOSYPROBLEM = _descriptor.Descriptor(
    name="BoSyProblem",
    full_name="BoSyProblem",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="specification",
            full_name="BoSyProblem.specification",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="optimize",
            full_name="BoSyProblem.optimize",
            index=1,
            number=2,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="timeout",
            full_name="BoSyProblem.timeout",
            index=2,
            number=3,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=57,
    serialized_end=147,
)

_BOSYSOLUTION = _descriptor.Descriptor(
    name="BoSySolution",
    full_name="BoSySolution",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="status",
            full_name="BoSySolution.status",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="system",
            full_name="BoSySolution.system",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=149,
    serialized_end=195,
)

_BOSYPROBLEM.fields_by_name[
    "specification"
].message_type = ml2_dot_tools_dot_protos_dot_ltl__pb2._LTLSPECIFICATION
DESCRIPTOR.message_types_by_name["BoSyProblem"] = _BOSYPROBLEM
DESCRIPTOR.message_types_by_name["BoSySolution"] = _BOSYSOLUTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BoSyProblem = _reflection.GeneratedProtocolMessageType(
    "BoSyProblem",
    (_message.Message,),
    {
        "DESCRIPTOR": _BOSYPROBLEM,
        "__module__": "ml2.tools.bosy.bosy_pb2"
        # @@protoc_insertion_point(class_scope:BoSyProblem)
    },
)
_sym_db.RegisterMessage(BoSyProblem)

BoSySolution = _reflection.GeneratedProtocolMessageType(
    "BoSySolution",
    (_message.Message,),
    {
        "DESCRIPTOR": _BOSYSOLUTION,
        "__module__": "ml2.tools.bosy.bosy_pb2"
        # @@protoc_insertion_point(class_scope:BoSySolution)
    },
)
_sym_db.RegisterMessage(BoSySolution)

_BOSY = _descriptor.ServiceDescriptor(
    name="BoSy",
    full_name="BoSy",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=197,
    serialized_end=303,
    methods=[
        _descriptor.MethodDescriptor(
            name="Synthesize",
            full_name="BoSy.Synthesize",
            index=0,
            containing_service=None,
            input_type=_BOSYPROBLEM,
            output_type=_BOSYSOLUTION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="SynthesizeStream",
            full_name="BoSy.SynthesizeStream",
            index=1,
            containing_service=None,
            input_type=_BOSYPROBLEM,
            output_type=_BOSYSOLUTION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_BOSY)

DESCRIPTOR.services_by_name["BoSy"] = _BOSY

# @@protoc_insertion_point(module_scope)
