"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RandLTLArgs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NUM_FORMULAS_FIELD_NUMBER: builtins.int
    NUM_APS_FIELD_NUMBER: builtins.int
    APS_FIELD_NUMBER: builtins.int
    ALLOW_DUPS_FIELD_NUMBER: builtins.int
    OUTPUT_FIELD_NUMBER: builtins.int
    SEED_FIELD_NUMBER: builtins.int
    SIMPLIFY_FIELD_NUMBER: builtins.int
    TREE_SIZE_FIELD_NUMBER: builtins.int
    BOOLEAN_PRIORITIES_FIELD_NUMBER: builtins.int
    LTL_PRIORITIES_FIELD_NUMBER: builtins.int
    SERE_PRIORITIES_FIELD_NUMBER: builtins.int
    num_formulas: builtins.int
    num_aps: builtins.int
    @property
    def aps(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    allow_dups: builtins.bool
    output: builtins.str
    seed: builtins.int
    simplify: builtins.int
    tree_size: builtins.int
    boolean_priorities: builtins.str
    ltl_priorities: builtins.str
    sere_priorities: builtins.str
    def __init__(
        self,
        *,
        num_formulas: builtins.int = ...,
        num_aps: builtins.int = ...,
        aps: collections.abc.Iterable[builtins.str] | None = ...,
        allow_dups: builtins.bool = ...,
        output: builtins.str = ...,
        seed: builtins.int = ...,
        simplify: builtins.int = ...,
        tree_size: builtins.int = ...,
        boolean_priorities: builtins.str = ...,
        ltl_priorities: builtins.str = ...,
        sere_priorities: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["allow_dups", b"allow_dups", "aps", b"aps", "boolean_priorities", b"boolean_priorities", "ltl_priorities", b"ltl_priorities", "num_aps", b"num_aps", "num_formulas", b"num_formulas", "output", b"output", "seed", b"seed", "sere_priorities", b"sere_priorities", "simplify", b"simplify", "tree_size", b"tree_size"]) -> None: ...

global___RandLTLArgs = RandLTLArgs
