# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/grpc/ltl/ltl.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ml2/grpc/ltl/ltl.proto\"/\n\nLTLFormula\x12\x0f\n\x07\x66ormula\x18\x01 \x01(\t\x12\x10\n\x08notation\x18\x02 \x01(\t\"|\n\x16\x44\x65\x63ompLTLSpecification\x12\x0e\n\x06inputs\x18\x01 \x03(\t\x12\x0f\n\x07outputs\x18\x02 \x03(\t\x12\x1f\n\nguarantees\x18\x03 \x03(\x0b\x32\x0b.LTLFormula\x12 \n\x0b\x61ssumptions\x18\x04 \x03(\x0b\x32\x0b.LTLFormula\"Q\n\x10LTLSpecification\x12\x0e\n\x06inputs\x18\x01 \x03(\t\x12\x0f\n\x07outputs\x18\x02 \x03(\t\x12\x1c\n\x07\x66ormula\x18\x03 \x01(\x0b\x32\x0b.LTLFormulab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml2.grpc.ltl.ltl_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LTLFORMULA']._serialized_start=26
  _globals['_LTLFORMULA']._serialized_end=73
  _globals['_DECOMPLTLSPECIFICATION']._serialized_start=75
  _globals['_DECOMPLTLSPECIFICATION']._serialized_end=199
  _globals['_LTLSPECIFICATION']._serialized_start=201
  _globals['_LTLSPECIFICATION']._serialized_end=282
# @@protoc_insertion_point(module_scope)
