# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/grpc/ltl/ltl.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ml2/grpc/ltl/ltl.proto\"/\n\nLTLFormula\x12\x0f\n\x07\x66ormula\x18\x01 \x01(\t\x12\x10\n\x08notation\x18\x02 \x01(\t\"\x98\x01\n\rLTLProperties\x12\x0e\n\x06inputs\x18\x01 \x03(\t\x12\x0f\n\x07outputs\x18\x02 \x03(\t\x12$\n\tsub_exprs\x18\x03 \x03(\x0b\x32\x11.LTLSpecification\x12\x11\n\x04name\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tsemantics\x18\x05 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_nameB\x0c\n\n_semantics\"\x9b\x02\n\x16\x44\x65\x63ompLTLSpecification\x12\x0e\n\x06inputs\x18\x01 \x03(\t\x12\x0f\n\x07outputs\x18\x02 \x03(\t\x12\x1f\n\nguarantees\x18\x03 \x03(\x0b\x32\x0b.LTLFormula\x12 \n\x0b\x61ssumptions\x18\x04 \x03(\x0b\x32\x0b.LTLFormula\x12,\n\x14guarantee_properties\x18\x05 \x01(\x0b\x32\x0e.LTLProperties\x12-\n\x15\x61ssumption_properties\x18\x06 \x01(\x0b\x32\x0e.LTLProperties\x12\x16\n\tsemantics\x18\x07 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x08 \x01(\tH\x01\x88\x01\x01\x42\x0c\n\n_semanticsB\x07\n\x05_name\"\x93\x01\n\x10LTLSpecification\x12\x0e\n\x06inputs\x18\x01 \x03(\t\x12\x0f\n\x07outputs\x18\x02 \x03(\t\x12\x1c\n\x07\x66ormula\x18\x03 \x01(\x0b\x32\x0b.LTLFormula\x12\x16\n\tsemantics\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x06 \x01(\tH\x01\x88\x01\x01\x42\x0c\n\n_semanticsB\x07\n\x05_nameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml2.grpc.ltl.ltl_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LTLFORMULA']._serialized_start=26
  _globals['_LTLFORMULA']._serialized_end=73
  _globals['_LTLPROPERTIES']._serialized_start=76
  _globals['_LTLPROPERTIES']._serialized_end=228
  _globals['_DECOMPLTLSPECIFICATION']._serialized_start=231
  _globals['_DECOMPLTLSPECIFICATION']._serialized_end=514
  _globals['_LTLSPECIFICATION']._serialized_start=517
  _globals['_LTLSPECIFICATION']._serialized_end=664
# @@protoc_insertion_point(module_scope)
