# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/grpc/ltl/ltl_mc.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from ml2.grpc.aiger import aiger_pb2 as ml2_dot_grpc_dot_aiger_dot_aiger__pb2
from ml2.grpc.ltl import ltl_pb2 as ml2_dot_grpc_dot_ltl_dot_ltl__pb2
from ml2.grpc.mealy import mealy_pb2 as ml2_dot_grpc_dot_mealy_dot_mealy__pb2
from ml2.grpc.tools import tools_pb2 as ml2_dot_grpc_dot_tools_dot_tools__pb2
from ml2.grpc.trace import trace_pb2 as ml2_dot_grpc_dot_trace_dot_trace__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ml2/grpc/ltl/ltl_mc.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1aml2/grpc/aiger/aiger.proto\x1a\x16ml2/grpc/ltl/ltl.proto\x1a\x1aml2/grpc/mealy/mealy.proto\x1a\x1aml2/grpc/tools/tools.proto\x1a\x1aml2/grpc/trace/trace.proto\"\xda\x02\n\x0cLTLMCProblem\x12\x31\n\nparameters\x18\x01 \x03(\x0b\x32\x1d.LTLMCProblem.ParametersEntry\x12\x37\n\x14\x64\x65\x63omp_specification\x18\x02 \x01(\x0b\x32\x17.DecompLTLSpecificationH\x00\x12\x32\n\x15\x66ormula_specification\x18\x03 \x01(\x0b\x32\x11.LTLSpecificationH\x00\x12 \n\x07\x63ircuit\x18\x04 \x01(\x0b\x32\r.AigerCircuitH\x01\x12&\n\rmealy_machine\x18\x05 \x01(\x0b\x32\r.MealyMachineH\x01\x12\x12\n\nrealizable\x18\x06 \x01(\x08\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0f\n\rspecificationB\x08\n\x06system\"\xc3\x01\n\rLTLMCSolution\x12\x1c\n\x06status\x18\x01 \x01(\x0e\x32\x0c.LTLMCStatus\x12\x17\n\x0f\x64\x65tailed_status\x18\x02 \x01(\t\x12\x0c\n\x04tool\x18\x03 \x01(\t\x12#\n\x0e\x63ounterexample\x18\x04 \x01(\x0b\x32\x06.TraceH\x00\x88\x01\x01\x12,\n\x04time\x18\x05 \x01(\x0b\x32\x19.google.protobuf.DurationH\x01\x88\x01\x01\x42\x11\n\x0f_counterexampleB\x07\n\x05_time*\xc4\x01\n\x0bLTLMCStatus\x12\x1b\n\x17LTLMCSTATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15LTLMCSTATUS_SATISFIED\x10\x01\x12\x18\n\x14LTLMCSTATUS_VIOLATED\x10\x02\x12\x15\n\x11LTLMCSTATUS_ERROR\x10\x03\x12\x17\n\x13LTLMCSTATUS_TIMEOUT\x10\x04\x12\x17\n\x13LTLMCSTATUS_INVALID\x10\x05\x12\x1a\n\x16LTLMCSTATUS_NONSUCCESS\x10\x06\x32\xe9\x01\n\x16GenericLTLModelChecker\x12(\n\x05Setup\x12\r.SetupRequest\x1a\x0e.SetupResponse\"\x00\x12=\n\x08Identify\x12\x16.IdentificationRequest\x1a\x17.IdentificationResponse\"\x00\x12-\n\nModelCheck\x12\r.LTLMCProblem\x1a\x0e.LTLMCSolution\"\x00\x12\x37\n\x10ModelCheckStream\x12\r.LTLMCProblem\x1a\x0e.LTLMCSolution\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml2.grpc.ltl.ltl_mc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LTLMCPROBLEM_PARAMETERSENTRY']._options = None
  _globals['_LTLMCPROBLEM_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_LTLMCSTATUS']._serialized_start=745
  _globals['_LTLMCSTATUS']._serialized_end=941
  _globals['_LTLMCPROBLEM']._serialized_start=198
  _globals['_LTLMCPROBLEM']._serialized_end=544
  _globals['_LTLMCPROBLEM_PARAMETERSENTRY']._serialized_start=468
  _globals['_LTLMCPROBLEM_PARAMETERSENTRY']._serialized_end=517
  _globals['_LTLMCSOLUTION']._serialized_start=547
  _globals['_LTLMCSOLUTION']._serialized_end=742
  _globals['_GENERICLTLMODELCHECKER']._serialized_start=944
  _globals['_GENERICLTLMODELCHECKER']._serialized_end=1177
# @@protoc_insertion_point(module_scope)
