# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/grpc/ltl/ltl_equiv.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ml2.grpc.trace import trace_pb2 as ml2_dot_grpc_dot_trace_dot_trace__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cml2/grpc/ltl/ltl_equiv.proto\x1a\x1aml2/grpc/trace/trace.proto\"W\n\x0fLTLEquivProblem\x12\x10\n\x08\x66ormula1\x18\x01 \x01(\t\x12\x10\n\x08\x66ormula2\x18\x02 \x01(\t\x12\x14\n\x07timeout\x18\x03 \x01(\x02H\x00\x88\x01\x01\x42\n\n\x08_timeout\"v\n\x10LTLEquivSolution\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\x04time\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12#\n\x0e\x65xclusive_word\x18\x03 \x01(\x0b\x32\x06.TraceH\x01\x88\x01\x01\x42\x07\n\x05_timeB\x11\n\x0f_exclusive_wordb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml2.grpc.ltl.ltl_equiv_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LTLEQUIVPROBLEM']._serialized_start=60
  _globals['_LTLEQUIVPROBLEM']._serialized_end=147
  _globals['_LTLEQUIVSOLUTION']._serialized_start=149
  _globals['_LTLEQUIVSOLUTION']._serialized_end=267
# @@protoc_insertion_point(module_scope)
