# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/tools/protos/ltl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ml2/tools/protos/ltl.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aml2/tools/protos/ltl.proto\"1\n\rLTLSatProblem\x12\x0f\n\x07\x66ormula\x18\x01 \x01(\t\x12\x0f\n\x07timeout\x18\x02 \x01(\x02\"/\n\x0eLTLSatSolution\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05trace\x18\x02 \x01(\t\"\\\n\x10LTLSpecification\x12\x0e\n\x06inputs\x18\x01 \x03(\t\x12\x0f\n\x07outputs\x18\x02 \x03(\t\x12\x12\n\nguarantees\x18\x03 \x03(\t\x12\x13\n\x0b\x61ssumptions\x18\x04 \x03(\tb\x06proto3'
)




_LTLSATPROBLEM = _descriptor.Descriptor(
  name='LTLSatProblem',
  full_name='LTLSatProblem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='formula', full_name='LTLSatProblem.formula', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='LTLSatProblem.timeout', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=79,
)


_LTLSATSOLUTION = _descriptor.Descriptor(
  name='LTLSatSolution',
  full_name='LTLSatSolution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='LTLSatSolution.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trace', full_name='LTLSatSolution.trace', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=128,
)


_LTLSPECIFICATION = _descriptor.Descriptor(
  name='LTLSpecification',
  full_name='LTLSpecification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs', full_name='LTLSpecification.inputs', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='LTLSpecification.outputs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guarantees', full_name='LTLSpecification.guarantees', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assumptions', full_name='LTLSpecification.assumptions', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=222,
)

DESCRIPTOR.message_types_by_name['LTLSatProblem'] = _LTLSATPROBLEM
DESCRIPTOR.message_types_by_name['LTLSatSolution'] = _LTLSATSOLUTION
DESCRIPTOR.message_types_by_name['LTLSpecification'] = _LTLSPECIFICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LTLSatProblem = _reflection.GeneratedProtocolMessageType('LTLSatProblem', (_message.Message,), {
  'DESCRIPTOR' : _LTLSATPROBLEM,
  '__module__' : 'ml2.tools.protos.ltl_pb2'
  # @@protoc_insertion_point(class_scope:LTLSatProblem)
  })
_sym_db.RegisterMessage(LTLSatProblem)

LTLSatSolution = _reflection.GeneratedProtocolMessageType('LTLSatSolution', (_message.Message,), {
  'DESCRIPTOR' : _LTLSATSOLUTION,
  '__module__' : 'ml2.tools.protos.ltl_pb2'
  # @@protoc_insertion_point(class_scope:LTLSatSolution)
  })
_sym_db.RegisterMessage(LTLSatSolution)

LTLSpecification = _reflection.GeneratedProtocolMessageType('LTLSpecification', (_message.Message,), {
  'DESCRIPTOR' : _LTLSPECIFICATION,
  '__module__' : 'ml2.tools.protos.ltl_pb2'
  # @@protoc_insertion_point(class_scope:LTLSpecification)
  })
_sym_db.RegisterMessage(LTLSpecification)


# @@protoc_insertion_point(module_scope)
