# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/grpc/trace/trace.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aml2/grpc/trace/trace.proto\"\x16\n\x05Trace\x12\r\n\x05trace\x18\x01 \x01(\tb\x06proto3')



_TRACE = DESCRIPTOR.message_types_by_name['Trace']
Trace = _reflection.GeneratedProtocolMessageType('Trace', (_message.Message,), {
  'DESCRIPTOR' : _TRACE,
  '__module__' : 'ml2.grpc.trace.trace_pb2'
  # @@protoc_insertion_point(class_scope:Trace)
  })
_sym_db.RegisterMessage(Trace)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRACE._serialized_start=30
  _TRACE._serialized_end=52
# @@protoc_insertion_point(module_scope)
