# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/tools/aalta/aalta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from ml2.tools.protos import ltl_pb2 as ml2_dot_tools_dot_protos_dot_ltl__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="ml2/tools/aalta/aalta.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1bml2/tools/aalta/aalta.proto\x1a\x1aml2/tools/protos/ltl.proto26\n\x05\x41\x61lta\x12-\n\x08\x43heckSat\x12\x0e.LTLSatProblem\x1a\x0f.LTLSatSolution"\x00\x62\x06proto3',
    dependencies=[
        ml2_dot_tools_dot_protos_dot_ltl__pb2.DESCRIPTOR,
    ],
)

_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_AALTA = _descriptor.ServiceDescriptor(
    name="Aalta",
    full_name="Aalta",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=59,
    serialized_end=113,
    methods=[
        _descriptor.MethodDescriptor(
            name="CheckSat",
            full_name="Aalta.CheckSat",
            index=0,
            containing_service=None,
            input_type=ml2_dot_tools_dot_protos_dot_ltl__pb2._LTLSATPROBLEM,
            output_type=ml2_dot_tools_dot_protos_dot_ltl__pb2._LTLSATSOLUTION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_AALTA)

DESCRIPTOR.services_by_name["Aalta"] = _AALTA

# @@protoc_insertion_point(module_scope)
