# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/grpc/limboole/limboole.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ml2.grpc.prop import prop_pb2 as ml2_dot_grpc_dot_prop_dot_prop__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ml2/grpc/limboole/limboole.proto\x1a\x18ml2/grpc/prop/prop.proto2n\n\x08Limboole\x12/\n\x08\x43heckSat\x12\x0f.PropSatProblem\x1a\x10.PropSatSolution\"\x00\x12\x31\n\nCheckValid\x12\x0f.PropSatProblem\x1a\x10.PropSatSolution\"\x00\x62\x06proto3')



_LIMBOOLE = DESCRIPTOR.services_by_name['Limboole']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIMBOOLE._serialized_start=62
  _LIMBOOLE._serialized_end=172
# @@protoc_insertion_point(module_scope)
