# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/tools/spot/spot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ml2.tools.protos import ltl_pb2 as ml2_dot_tools_dot_protos_dot_ltl__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ml2/tools/spot/spot.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19ml2/tools/spot/spot.proto\x1a\x1aml2/tools/protos/ltl.proto\"\xe5\x01\n\x0bRandLTLArgs\x12\x14\n\x0cnum_formulas\x18\x01 \x01(\x05\x12\x0f\n\x07num_aps\x18\x02 \x01(\x05\x12\x0b\n\x03\x61ps\x18\x03 \x03(\t\x12\x12\n\nallow_dups\x18\x04 \x01(\x08\x12\x0e\n\x06output\x18\x05 \x01(\t\x12\x0c\n\x04seed\x18\x06 \x01(\x05\x12\x10\n\x08simplify\x18\x07 \x01(\x05\x12\x11\n\ttree_size\x18\x08 \x01(\x05\x12\x1a\n\x12\x62oolean_priorities\x18\t \x01(\t\x12\x16\n\x0eltl_priorities\x18\n \x01(\t\x12\x17\n\x0fsere_priorities\x18\x0b \x01(\t2\x92\x01\n\x04Spot\x12-\n\x08\x43heckSat\x12\x0e.LTLSatProblem\x1a\x0f.LTLSatSolution\"\x00\x12\x31\n\x07MCTrace\x12\x12.LTLTraceMCProblem\x1a\x10.TraceMCSolution\"\x00\x12(\n\x07RandLTL\x12\x0c.RandLTLArgs\x1a\x0b.LTLFormula\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[ml2_dot_tools_dot_protos_dot_ltl__pb2.DESCRIPTOR,])




_RANDLTLARGS = _descriptor.Descriptor(
  name='RandLTLArgs',
  full_name='RandLTLArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_formulas', full_name='RandLTLArgs.num_formulas', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_aps', full_name='RandLTLArgs.num_aps', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aps', full_name='RandLTLArgs.aps', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allow_dups', full_name='RandLTLArgs.allow_dups', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output', full_name='RandLTLArgs.output', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seed', full_name='RandLTLArgs.seed', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='simplify', full_name='RandLTLArgs.simplify', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tree_size', full_name='RandLTLArgs.tree_size', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boolean_priorities', full_name='RandLTLArgs.boolean_priorities', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ltl_priorities', full_name='RandLTLArgs.ltl_priorities', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sere_priorities', full_name='RandLTLArgs.sere_priorities', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=287,
)

DESCRIPTOR.message_types_by_name['RandLTLArgs'] = _RANDLTLARGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RandLTLArgs = _reflection.GeneratedProtocolMessageType('RandLTLArgs', (_message.Message,), {
  'DESCRIPTOR' : _RANDLTLARGS,
  '__module__' : 'ml2.tools.spot.spot_pb2'
  # @@protoc_insertion_point(class_scope:RandLTLArgs)
  })
_sym_db.RegisterMessage(RandLTLArgs)



_SPOT = _descriptor.ServiceDescriptor(
  name='Spot',
  full_name='Spot',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=290,
  serialized_end=436,
  methods=[
  _descriptor.MethodDescriptor(
    name='CheckSat',
    full_name='Spot.CheckSat',
    index=0,
    containing_service=None,
    input_type=ml2_dot_tools_dot_protos_dot_ltl__pb2._LTLSATPROBLEM,
    output_type=ml2_dot_tools_dot_protos_dot_ltl__pb2._LTLSATSOLUTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MCTrace',
    full_name='Spot.MCTrace',
    index=1,
    containing_service=None,
    input_type=ml2_dot_tools_dot_protos_dot_ltl__pb2._LTLTRACEMCPROBLEM,
    output_type=ml2_dot_tools_dot_protos_dot_ltl__pb2._TRACEMCSOLUTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RandLTL',
    full_name='Spot.RandLTL',
    index=2,
    containing_service=None,
    input_type=_RANDLTLARGS,
    output_type=ml2_dot_tools_dot_protos_dot_ltl__pb2._LTLFORMULA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPOT)

DESCRIPTOR.services_by_name['Spot'] = _SPOT

# @@protoc_insertion_point(module_scope)
