# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/grpc/prop/prop.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18ml2/grpc/prop/prop.proto\"2\n\x0ePropSatProblem\x12\x0f\n\x07\x66ormula\x18\x01 \x01(\t\x12\x0f\n\x07timeout\x18\x02 \x01(\x02\"\x8a\x01\n\x0fPropSatSolution\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x34\n\nassignment\x18\x02 \x03(\x0b\x32 .PropSatSolution.AssignmentEntry\x1a\x31\n\x0f\x41ssignmentEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x1a\n\x06\x43lause\x12\x10\n\x08literals\x18\x01 \x03(\x05\";\n\tResClause\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08literals\x18\x02 \x03(\x05\x12\x10\n\x08premises\x18\x03 \x03(\x05\"u\n\nCNFFormula\x12\x10\n\x08num_vars\x18\x01 \x01(\x05\x12\x13\n\x0bnum_clauses\x18\x02 \x01(\x05\x12\x18\n\x07\x63lauses\x18\x03 \x03(\x0b\x32\x07.Clause\x12\x10\n\x08\x63omments\x18\x04 \x03(\t\x12\x14\n\x0csymbol_table\x18\x05 \x03(\t\">\n\rCNFSatProblem\x12\x1c\n\x07\x66ormula\x18\x01 \x01(\x0b\x32\x0b.CNFFormula\x12\x0f\n\x07timeout\x18\x02 \x01(\x02\"s\n\x0e\x43NFSatSolution\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nassignment\x18\x02 \x03(\x05\x12\x1e\n\rclausal_proof\x18\x03 \x03(\x0b\x32\x07.Clause\x12\x1d\n\tres_proof\x18\x04 \x03(\x0b\x32\n.ResClause\"B\n\x14ResProofCheckProblem\x12\x19\n\x05proof\x18\x01 \x03(\x0b\x32\n.ResClause\x12\x0f\n\x07timeout\x18\x02 \x01(\x02\"\'\n\x15ResProofCheckSolution\x12\x0e\n\x06status\x18\x01 \x01(\t\"a\n\x18\x43lausalProofCheckProblem\x12\x1c\n\x07\x66ormula\x18\x01 \x01(\x0b\x32\x0b.CNFFormula\x12\x16\n\x05proof\x18\x02 \x03(\x0b\x32\x07.Clause\x12\x0f\n\x07timeout\x18\x03 \x01(\x02\"%\n\x08ResProof\x12\x19\n\x05proof\x18\x01 \x03(\x0b\x32\n.ResClauseb\x06proto3')



_PROPSATPROBLEM = DESCRIPTOR.message_types_by_name['PropSatProblem']
_PROPSATSOLUTION = DESCRIPTOR.message_types_by_name['PropSatSolution']
_PROPSATSOLUTION_ASSIGNMENTENTRY = _PROPSATSOLUTION.nested_types_by_name['AssignmentEntry']
_CLAUSE = DESCRIPTOR.message_types_by_name['Clause']
_RESCLAUSE = DESCRIPTOR.message_types_by_name['ResClause']
_CNFFORMULA = DESCRIPTOR.message_types_by_name['CNFFormula']
_CNFSATPROBLEM = DESCRIPTOR.message_types_by_name['CNFSatProblem']
_CNFSATSOLUTION = DESCRIPTOR.message_types_by_name['CNFSatSolution']
_RESPROOFCHECKPROBLEM = DESCRIPTOR.message_types_by_name['ResProofCheckProblem']
_RESPROOFCHECKSOLUTION = DESCRIPTOR.message_types_by_name['ResProofCheckSolution']
_CLAUSALPROOFCHECKPROBLEM = DESCRIPTOR.message_types_by_name['ClausalProofCheckProblem']
_RESPROOF = DESCRIPTOR.message_types_by_name['ResProof']
PropSatProblem = _reflection.GeneratedProtocolMessageType('PropSatProblem', (_message.Message,), {
  'DESCRIPTOR' : _PROPSATPROBLEM,
  '__module__' : 'ml2.grpc.prop.prop_pb2'
  # @@protoc_insertion_point(class_scope:PropSatProblem)
  })
_sym_db.RegisterMessage(PropSatProblem)

PropSatSolution = _reflection.GeneratedProtocolMessageType('PropSatSolution', (_message.Message,), {

  'AssignmentEntry' : _reflection.GeneratedProtocolMessageType('AssignmentEntry', (_message.Message,), {
    'DESCRIPTOR' : _PROPSATSOLUTION_ASSIGNMENTENTRY,
    '__module__' : 'ml2.grpc.prop.prop_pb2'
    # @@protoc_insertion_point(class_scope:PropSatSolution.AssignmentEntry)
    })
  ,
  'DESCRIPTOR' : _PROPSATSOLUTION,
  '__module__' : 'ml2.grpc.prop.prop_pb2'
  # @@protoc_insertion_point(class_scope:PropSatSolution)
  })
_sym_db.RegisterMessage(PropSatSolution)
_sym_db.RegisterMessage(PropSatSolution.AssignmentEntry)

Clause = _reflection.GeneratedProtocolMessageType('Clause', (_message.Message,), {
  'DESCRIPTOR' : _CLAUSE,
  '__module__' : 'ml2.grpc.prop.prop_pb2'
  # @@protoc_insertion_point(class_scope:Clause)
  })
_sym_db.RegisterMessage(Clause)

ResClause = _reflection.GeneratedProtocolMessageType('ResClause', (_message.Message,), {
  'DESCRIPTOR' : _RESCLAUSE,
  '__module__' : 'ml2.grpc.prop.prop_pb2'
  # @@protoc_insertion_point(class_scope:ResClause)
  })
_sym_db.RegisterMessage(ResClause)

CNFFormula = _reflection.GeneratedProtocolMessageType('CNFFormula', (_message.Message,), {
  'DESCRIPTOR' : _CNFFORMULA,
  '__module__' : 'ml2.grpc.prop.prop_pb2'
  # @@protoc_insertion_point(class_scope:CNFFormula)
  })
_sym_db.RegisterMessage(CNFFormula)

CNFSatProblem = _reflection.GeneratedProtocolMessageType('CNFSatProblem', (_message.Message,), {
  'DESCRIPTOR' : _CNFSATPROBLEM,
  '__module__' : 'ml2.grpc.prop.prop_pb2'
  # @@protoc_insertion_point(class_scope:CNFSatProblem)
  })
_sym_db.RegisterMessage(CNFSatProblem)

CNFSatSolution = _reflection.GeneratedProtocolMessageType('CNFSatSolution', (_message.Message,), {
  'DESCRIPTOR' : _CNFSATSOLUTION,
  '__module__' : 'ml2.grpc.prop.prop_pb2'
  # @@protoc_insertion_point(class_scope:CNFSatSolution)
  })
_sym_db.RegisterMessage(CNFSatSolution)

ResProofCheckProblem = _reflection.GeneratedProtocolMessageType('ResProofCheckProblem', (_message.Message,), {
  'DESCRIPTOR' : _RESPROOFCHECKPROBLEM,
  '__module__' : 'ml2.grpc.prop.prop_pb2'
  # @@protoc_insertion_point(class_scope:ResProofCheckProblem)
  })
_sym_db.RegisterMessage(ResProofCheckProblem)

ResProofCheckSolution = _reflection.GeneratedProtocolMessageType('ResProofCheckSolution', (_message.Message,), {
  'DESCRIPTOR' : _RESPROOFCHECKSOLUTION,
  '__module__' : 'ml2.grpc.prop.prop_pb2'
  # @@protoc_insertion_point(class_scope:ResProofCheckSolution)
  })
_sym_db.RegisterMessage(ResProofCheckSolution)

ClausalProofCheckProblem = _reflection.GeneratedProtocolMessageType('ClausalProofCheckProblem', (_message.Message,), {
  'DESCRIPTOR' : _CLAUSALPROOFCHECKPROBLEM,
  '__module__' : 'ml2.grpc.prop.prop_pb2'
  # @@protoc_insertion_point(class_scope:ClausalProofCheckProblem)
  })
_sym_db.RegisterMessage(ClausalProofCheckProblem)

ResProof = _reflection.GeneratedProtocolMessageType('ResProof', (_message.Message,), {
  'DESCRIPTOR' : _RESPROOF,
  '__module__' : 'ml2.grpc.prop.prop_pb2'
  # @@protoc_insertion_point(class_scope:ResProof)
  })
_sym_db.RegisterMessage(ResProof)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROPSATSOLUTION_ASSIGNMENTENTRY._options = None
  _PROPSATSOLUTION_ASSIGNMENTENTRY._serialized_options = b'8\001'
  _PROPSATPROBLEM._serialized_start=28
  _PROPSATPROBLEM._serialized_end=78
  _PROPSATSOLUTION._serialized_start=81
  _PROPSATSOLUTION._serialized_end=219
  _PROPSATSOLUTION_ASSIGNMENTENTRY._serialized_start=170
  _PROPSATSOLUTION_ASSIGNMENTENTRY._serialized_end=219
  _CLAUSE._serialized_start=221
  _CLAUSE._serialized_end=247
  _RESCLAUSE._serialized_start=249
  _RESCLAUSE._serialized_end=308
  _CNFFORMULA._serialized_start=310
  _CNFFORMULA._serialized_end=427
  _CNFSATPROBLEM._serialized_start=429
  _CNFSATPROBLEM._serialized_end=491
  _CNFSATSOLUTION._serialized_start=493
  _CNFSATSOLUTION._serialized_end=608
  _RESPROOFCHECKPROBLEM._serialized_start=610
  _RESPROOFCHECKPROBLEM._serialized_end=676
  _RESPROOFCHECKSOLUTION._serialized_start=678
  _RESPROOFCHECKSOLUTION._serialized_end=717
  _CLAUSALPROOFCHECKPROBLEM._serialized_start=719
  _CLAUSALPROOFCHECKPROBLEM._serialized_end=816
  _RESPROOF._serialized_start=818
  _RESPROOF._serialized_end=855
# @@protoc_insertion_point(module_scope)
