# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/grpc/prop/prop.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18ml2/grpc/prop/prop.proto"2\n\x0ePropSatProblem\x12\x0f\n\x07\x66ormula\x18\x01 \x01(\t\x12\x0f\n\x07timeout\x18\x02 \x01(\x02"\x8a\x01\n\x0fPropSatSolution\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x34\n\nassignment\x18\x02 \x03(\x0b\x32 .PropSatSolution.AssignmentEntry\x1a\x31\n\x0f\x41ssignmentEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01"\x1a\n\x06\x43lause\x12\x10\n\x08literals\x18\x01 \x03(\x05";\n\tResClause\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08literals\x18\x02 \x03(\x05\x12\x10\n\x08premises\x18\x03 \x03(\x05"u\n\nCNFFormula\x12\x10\n\x08num_vars\x18\x01 \x01(\x05\x12\x13\n\x0bnum_clauses\x18\x02 \x01(\x05\x12\x18\n\x07\x63lauses\x18\x03 \x03(\x0b\x32\x07.Clause\x12\x10\n\x08\x63omments\x18\x04 \x03(\t\x12\x14\n\x0csymbol_table\x18\x05 \x03(\t">\n\rCNFSatProblem\x12\x1c\n\x07\x66ormula\x18\x01 \x01(\x0b\x32\x0b.CNFFormula\x12\x0f\n\x07timeout\x18\x02 \x01(\x02"\x8f\x01\n\x0e\x43NFSatSolution\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nassignment\x18\x02 \x03(\x05\x12\x1e\n\rclausal_proof\x18\x03 \x03(\x0b\x32\x07.Clause\x12\x1d\n\tres_proof\x18\x04 \x03(\x0b\x32\n.ResClause\x12\x11\n\x04time\x18\x05 \x01(\x02H\x00\x88\x01\x01\x42\x07\n\x05_time"B\n\x14ResProofCheckProblem\x12\x19\n\x05proof\x18\x01 \x03(\x0b\x32\n.ResClause\x12\x0f\n\x07timeout\x18\x02 \x01(\x02"\'\n\x15ResProofCheckSolution\x12\x0e\n\x06status\x18\x01 \x01(\t"a\n\x18\x43lausalProofCheckProblem\x12\x1c\n\x07\x66ormula\x18\x01 \x01(\x0b\x32\x0b.CNFFormula\x12\x16\n\x05proof\x18\x02 \x03(\x0b\x32\x07.Clause\x12\x0f\n\x07timeout\x18\x03 \x01(\x02"%\n\x08ResProof\x12\x19\n\x05proof\x18\x01 \x03(\x0b\x32\n.ResClauseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ml2.grpc.prop.prop_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_PROPSATSOLUTION_ASSIGNMENTENTRY"]._options = None
    _globals["_PROPSATSOLUTION_ASSIGNMENTENTRY"]._serialized_options = b"8\001"
    _globals["_PROPSATPROBLEM"]._serialized_start = 28
    _globals["_PROPSATPROBLEM"]._serialized_end = 78
    _globals["_PROPSATSOLUTION"]._serialized_start = 81
    _globals["_PROPSATSOLUTION"]._serialized_end = 219
    _globals["_PROPSATSOLUTION_ASSIGNMENTENTRY"]._serialized_start = 170
    _globals["_PROPSATSOLUTION_ASSIGNMENTENTRY"]._serialized_end = 219
    _globals["_CLAUSE"]._serialized_start = 221
    _globals["_CLAUSE"]._serialized_end = 247
    _globals["_RESCLAUSE"]._serialized_start = 249
    _globals["_RESCLAUSE"]._serialized_end = 308
    _globals["_CNFFORMULA"]._serialized_start = 310
    _globals["_CNFFORMULA"]._serialized_end = 427
    _globals["_CNFSATPROBLEM"]._serialized_start = 429
    _globals["_CNFSATPROBLEM"]._serialized_end = 491
    _globals["_CNFSATSOLUTION"]._serialized_start = 494
    _globals["_CNFSATSOLUTION"]._serialized_end = 637
    _globals["_RESPROOFCHECKPROBLEM"]._serialized_start = 639
    _globals["_RESPROOFCHECKPROBLEM"]._serialized_end = 705
    _globals["_RESPROOFCHECKSOLUTION"]._serialized_start = 707
    _globals["_RESPROOFCHECKSOLUTION"]._serialized_end = 746
    _globals["_CLAUSALPROOFCHECKPROBLEM"]._serialized_start = 748
    _globals["_CLAUSALPROOFCHECKPROBLEM"]._serialized_end = 845
    _globals["_RESPROOF"]._serialized_start = 847
    _globals["_RESPROOF"]._serialized_end = 884
# @@protoc_insertion_point(module_scope)
