# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml2/tools/limboole/limboole.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ml2.tools.protos import prop_pb2 as ml2_dot_tools_dot_protos_dot_prop__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="ml2/tools/limboole/limboole.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n!ml2/tools/limboole/limboole.proto\x1a\x1bml2/tools/protos/prop.proto2n\n\x08Limboole\x12/\n\x08\x43heckSat\x12\x0f.PropSatProblem\x1a\x10.PropSatSolution"\x00\x12\x31\n\nCheckValid\x12\x0f.PropSatProblem\x1a\x10.PropSatSolution"\x00\x62\x06proto3',
    dependencies=[
        ml2_dot_tools_dot_protos_dot_prop__pb2.DESCRIPTOR,
    ],
)


_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_LIMBOOLE = _descriptor.ServiceDescriptor(
    name="Limboole",
    full_name="Limboole",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=66,
    serialized_end=176,
    methods=[
        _descriptor.MethodDescriptor(
            name="CheckSat",
            full_name="Limboole.CheckSat",
            index=0,
            containing_service=None,
            input_type=ml2_dot_tools_dot_protos_dot_prop__pb2._PROPSATPROBLEM,
            output_type=ml2_dot_tools_dot_protos_dot_prop__pb2._PROPSATSOLUTION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="CheckValid",
            full_name="Limboole.CheckValid",
            index=1,
            containing_service=None,
            input_type=ml2_dot_tools_dot_protos_dot_prop__pb2._PROPSATPROBLEM,
            output_type=ml2_dot_tools_dot_protos_dot_prop__pb2._PROPSATSOLUTION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_LIMBOOLE)

DESCRIPTOR.services_by_name["Limboole"] = _LIMBOOLE

# @@protoc_insertion_point(module_scope)
